consoles/consoles/urls.py
from django.contrib import admin
from django.urls import path, include

import core.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('games/', include('games.urls', namespace='games')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", core.views.HomePageView.as_view(), name="homepage"),
    path("test", core.views.test_view, name="test"),
]

consoles/games/urls.py
from django.urls import path

from . import views

app_name = "games"


urlpatterns = [
    path("characters/", views.CharacterListView.as_view(), name="character_list"),
    path("characters/<int:pk>", views.CharacterListView.as_view(), name="character_detail"),
    path("characters/new", views.CharacterCreateView.as_view(), name="character_create"),
    path("characters/update/<int:pk>", views.CharacterUpdateView.as_view(),
         name="character_update"),
    path("characters/delete/<int:pk>", views.CharacterDeleteView.as_view(),
         name="character_delete"),
    path("games/", views.GameListView.as_view(), name="game_list"),
    path("games/new", views.GameCreateView.as_view(), name="game_create"),
    path("games/<int:pk>", views.GameDetailView.as_view(),
         name="game_detail"),
    path("games/update/<int:pk>", views.GameUpdateView.as_view(),
         name="game_update"),
    path("games/delete/<int:pk>", views.GameDeleteView.as_view(),
         name="game_delete"),
    path("games/update_bis/<int:pk>", views.GameUpdatebisView.as_view(), name="game_update_bis",),
     path(
"games/update_bis/<int:pk>",
views.GameUpdatebisView.as_view(),
name="game_update_bis",
),
     path(
"games/bis/<int:pk>",
views.GameDetailbisView.as_view(),
name="game_detail_bis",
),
     
     path(
"games/js/<int:pk>",
views.GameDetailJsView.as_view(),
name="game_detail_js",
),
]

consoles/games/models.py
from django.db import models

# Create your models here.

class Character(models.Model):
    # PK id created by default id (bigint), you may override that with th e
    # following line
    # id = models.SmallIntegerField(auto_increment=True, primary_key=True)
    name = models.CharField(max_length=200, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
    		return self.name

class Game(models.Model):
    name = models.CharField(max_length=50, unique=True)
    characters = models.ManyToManyField(Character)
    release_date = models.DateTimeField()
    

    class Meta:
        ordering = ['name']

consoles/games/forms.py
from django import forms

from .models import Game

class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ['name', 'characters', 'release_date']
        widgets = {
            'release_date': forms.DateInput()
        }
        

consoles/games/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from .models import Character, Game
from .forms import GameForm
from django.forms.models import model_to_dict
from django.views import View
from django.views.generic.base import TemplateView
from django.http import JsonResponse


# Create your views here.


###################### ACTORS ##########################

class CharacterListView(ListView):
    model = Character

class CharacterCreateView(CreateView):
    model = Character
    fields = ['name']

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Character "{character_name}" has been created'.format(
                character_name=self.object.name))
        return response

    def get_success_url(self):
    	return reverse_lazy("games:character_detail", args=[self.object.id])

class CharacterDetailView(DetailView):
    model = Character

class CharacterUpdateView(UpdateView):
    model = Character
    fields = ['name']
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Character "{character_name}" has been updated'.format(
                character_name=self.object.name))
        return response
    
    # comment the following line to show the error about not having an
    # success_url
    def get_success_url(self):
        return reverse_lazy("games:character_detail", args=[self.object.id])
        # you can also use it this way with kwargs, just to let you know
        # but here we have only one argument, so no mistake can be done
        #return reverse_lazy("movies:actor_detail",
        #                    kwargs={'pk':self.object.id})


class CharacterDeleteView(DeleteView):
    model = Character
    success_url = reverse_lazy("games:character_list")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Character "{character_name}" has been deleted'.format(
                character_name=self.object.name))
        return response


###################### MOVIES ##########################


class GameListView(LoginRequiredMixin, ListView):
    model = Game


class GameDetailView(DetailView):
    model = Game


class GameCreateView(CreateView):
    model = Game
    form_class = GameForm

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Game "{game_name}" has been created'.format(
                game_name=self.object.name))
        return response

    # comment the following line to show the error about not having an
    # success_url
    def get_success_url(self):
        return reverse_lazy("games:game_detail", args=[self.object.id])
        # you can also use it this way with kwargs, just to let you know
        # but here we have only one argument, so no mistake can be done
        #return reverse_lazy("movies:actor_detail",
        #                    kwargs={'pk':self.object.id})



class GameUpdateView(UpdateView):
   model = Game
   form_class = GameForm

   def form_valid(self, form):
       response = super().form_valid(form)
       messages.add_message(
           self.request,
           messages.SUCCESS,
           'Game "{game_name}" has been updated'.format(
               game_name=self.object.name
           ),
       )
       return response

   def get_context_data(self, **kwargs):
       context = super().get_context_data(**kwargs)
       game_dico = model_to_dict(self.object)
       game_dico["release_date"] = game_dico["release_date"].strftime(
           "%Y-%m-%d"
       )
    #    number of characters
       characters = game_dico["characters"]
       game_character_list = []
       for character in characters:
           game_character_list.append({"id": character.id, "name": character.name})
       game_dico["characters"] = game_character_list
       character_list = list(Character.objects.all().values())
       context["game_dict"] = game_dico
       context["character_list"] = character_list
       print("context", context)
       return context

   # comment the following line to show the error about not having an
   # success_url
   def get_success_url(self):
       return reverse_lazy("games:game_detail", args=[self.object.id])
       # you can also use it this way with kwargs, just to let you know
       # but here we have only one argument, so no mistake can be done
       # return reverse_lazy("movies:actor_detail",
       #                    kwargs={'pk':self.object.id})

class GameDeleteView(DeleteView):
    model = Game
    success_url = reverse_lazy("games:game_list")
    
    def form_valid(self, form):
        response = super().form_valid(form)
        messages.add_message(
            self.request, messages.SUCCESS,
            'Game "{game_name}" has been deleted'.format(
                game_name=self.object.name))
        return response

class GameUpdatebisView(View):
   def post(self, request, *args, **kwargs):
       game = get_object_or_404(Game, pk=self.kwargs["pk"])
       # Create a form instance with POST data
       form = GameForm(request.POST, instance=game)
       if form.is_valid():
           form.save()
           return JsonResponse({"success": True})
       else:
           return JsonResponse({"success": False, "errors": form.errors})
       
class GameDetailbisView(TemplateView):
    template_name = "games/game_detailbis.html"
    def get(self, request, *args, **kwargs):
        game = get_object_or_404(Game, pk=self.kwargs["pk"])
        return super().get(request, *args, **kwargs)
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['game_id'] = self.kwargs["pk"]
        return context

class GameDetailJsView(View):
    def get(self, request, *args, **kwargs):
        game = get_object_or_404(Game, pk=self.kwargs["pk"])
        game_js = model_to_dict(game)
        game_js["characters"] = []
        for character in game.characters.values():
            game_js["characters"].append(character)
        return JsonResponse({"game": game_js})
    

consoles/games/templates/games/character_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete the character "{{ object.name }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>
{% endblock content %}

consoles/games/templates/games/character_detail.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'games:character_list' %}">Characters list</a><br/><br/>
<a href="{% url 'games:character_update' object.id %}">Update Character</a><br/>
<a href="{% url 'games:character_delete' object.id %}">Delete Character</a><br/>
<h1>{{ object.name }}</h1>
{% endblock content %}

consoles/games/templates/games/character_form.html
{% extends "base.html" %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
{% endblock content %}

consoles/games/templates/games/character_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'games:character_create' %}">New character</a><br/><br/>
{% for character in object_list %}
    <a href="{% url 'games:character_detail' character.id %}">{{ character.name }}</a><br/>
{% endfor %}
{% endblock content %}

consoles/games/templates/games/game_detail.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'games:game_list' %}">Games list</a><br/>
<a href="{% url 'games:game_update' object.id %}">Update Game</a><br/>
<a href="{% url 'games:game_delete' object.id %}">Delete Game</a><br/>
<h1>{{ object.name }}</h1>
Characters:<br/>
{% for character in object.characters.all %}
{{character.name}}<br/>
<br/>
Release date: {{object.release_date|date:"%d %B %Y"}}<br/>
{% endfor %}
{% endblock content %}

consoles/games/templates/games/game_detailbis.html
{% extends "base.html" %}
{% load django_vite %}
{% block content %}
<div id="app">
<app></app>
</div>
{% endblock content %}
{% block js %}
{{ block.super }}
<script>
var ext_game_id = {{ game_id }}
var ext_game_detail_js_url = '{% url 'games:game_detail_js' game_id %}'
</script>
{% vite_asset 'src/apps/game_show/game_show.js' %}
{% endblock js %}

consoles/games/templates/games/game_form.html
{% extends "base.html" %}
{% load django_vite %}

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary"
            @click.prevent="submit_form"
            :disabled="submitting_form">
            Submit
        </button>
    
</form> 

{% comment %} <form method="post">{% csrf_token %}
    {{ form.as_p }}
    <p>
        <label for="id_release_date">Release date:</label>
        <input type="hidden" name="release_date" :value="get_date_string" required=""
        id="id_release_date">
        <VueDatePicker style="display:inline-block;width:
        300px;padding-bottom:10px;padding-left:10px" v-model="date"
        :enable-time-picker="false"></VueDatePicker>
        </p>
    <input type="submit" value="Save">
    
</form> {% endcomment %}

<div id="app">
    <app>
        
    </app>
</div>
{% endblock content %}

{% block js %}
  {{ block.super }}
  <script>
       var ext_csrf_token = '{{ csrf_token }}'
       var ext_form = `{{ form.as_p | safe}}`
       var ext_game_dict = {{ game_dict | safe }}
       var ext_character_list = {{ character_list | safe }}
       {% comment %} var ext_update_bis_url = '{% url 'games:game_update_bis' object.id %}' {% endcomment %}
  </script>
  {% vite_hmr_client %}
  {% vite_asset 'src/apps/game_edit/game_edit.js' %}
{% endblock js %}

consoles/games/templates/games/game_list.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'games:game_create' %}">New Game</a><br/><br/>
{% for game in object_list %}
    <a href="{% url 'games:game_detail' game.id %}">{{ game.name }}</a><br/>
{% endfor %}
{% endblock content %}